repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
    - id: no-commit-to-branch
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: python-use-type-annotations
    - id: text-unicode-replacement-char
- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      args:
      - --in-place
      - --wrap-summaries=100
      - --wrap-descriptions=100
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
        - id: blacken-docs
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
        - id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args:
        - --strict
        - --implicit-reexport
        - --show-error-codes
        - --show-error-context
        - --show-column-numbers
        additional_dependencies:
            - types-cryptography==3.3.23.2
            - pytest-mypy==0.10.3
            - binapy==0.7.0
            - freezegun==1.2.2
