repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
        - id: blacken-docs
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        additional_dependencies:
            - toml
        args:
            - --add-ignore=D107
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies:
            - types-cryptography==3.3.21
            - types-requests==2.28.5
            - types-backports==0.1.3
            - backports.cached_property==1.0.2
            - pytest-mypy==0.9.1
            - binapy==0.6.0
