repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
    - id: no-commit-to-branch
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
        args:
        - --strict
        - --implicit-reexport
        - --show-error-codes
        - --show-error-context
        - --show-column-numbers
        additional_dependencies:
            - types-cryptography==3.3.23.2
            - pytest-mypy==0.10.3
            - binapy==0.8.0
            - freezegun==1.2.2
            - jwcrypto==1.5.0
