repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-check-blanket-type-ignore
    - id: python-no-eval
    - id: python-use-type-annotations
    - id: text-unicode-replacement-char
- repo: https://github.com/myint/docformatter
  rev: v1.7.2
  hooks:
    - id: docformatter
      args:
      - --in-place
      - --wrap-summaries=100
      - --wrap-descriptions=100
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.5
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
            - flake8-typing-imports==1.14.0
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.14.0
    hooks:
        - id: blacken-docs
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        additional_dependencies:
            - toml
        args:
            - --add-ignore=D107
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
    -   id: mypy
        args:
        - --strict
        - --implicit-reexport
        - --show-error-codes
        - --show-error-context
        - --show-column-numbers
        additional_dependencies:
            - types-cryptography==3.3.23.2
            - pytest-mypy==0.10.3
            - binapy==0.6.0
            - freezegun==1.2.2
