[tox]
isolated_build = true
envlist = py37, py38, py39, py310, py311, lint

[gh-actions]
python =
    3.11: py311
    3.10: py310
    3.9: py39
    3.8: py38
    3.7: py37

[testenv:lint]
allowlist_externals =
    isort
    black
    flake8
    poetry
    mkdocs
    twine
extras =
    test
    doc
commands =
    isort jwskate
    black jwskate tests
    poetry build
    mkdocs build

[testenv]
allowlist_externals =
    poetry
commands_pre =
    poetry install --no-root --sync -E test
passenv = *
setenv =
    PYTHONPATH = {toxinidir}
    PYTHONWARNINGS = ignore
commands =
    poetry run pytest -s --cov=jwskate --cov-append --cov-report=xml --cov-report term-missing tests
